GET http://127.0.0.1:5000/test


###
// invalid request body
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"email",
    "priority":1
}
###
// invalid request body field datatype
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"email",
    "priority":"1",
    "payload":"payload"
}

###
// test mode is absent
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"email",
    "payload":"payload",
    "priority":1
}

###
// test mode is present but invalid
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"email",
    "payload":"payload",
    "priority":1
}

###
// test mode is present and valid
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"download_file",
    "payload":{
        "url":"https://jsonplaceholder.typicode.com/todos/1",
        "filename":"dummy.json"
    },
    "priority":1
}


###
// send test email
POST http://127.0.0.1:5000/tasks HTTP/1.1
Content-Type: application/json

{
    "type":"send_email",
    "payload":{
        "client_name":"Client",
        "client_email":"bohomolyulian3022003@gmail.com",
        "recipient_name":"TestUser",
        "recipient_email":"elliotaldersonhome@gmail.com",
        "subject":"Test",
        "html_content":"<html><body><p>Test</p></body></html>"
    },
    "priority":2
}

# cmd
// add task --type download_file --payload '{"url":"https://jsonplaceholder.typicode.com/todos/1","filename":"dummy.json"}' --priority 1

// add task --type send_email --payload '{"url":"https://jsonplaceholder.typicode.com/todos/1","filename":"dummy.json"}' --priority 1